repos:
-   repo: local
    hooks:
    - id: pyupgrade
      name: pyupgrade
      entry: pyupgrade
      args: ['--py38-plus', '--keep-runtime-typing']
      language: system
      types: [python]
    # Configuration for black exists in pyproject.toml,
    # but we let pre-commit take care of the file filtering.
    - id: black
      name: black
      entry: black
      language: system
      types: [python]
    # Configuration for flake8 exists in setup.cfg,
    # but we let pre-commit take care of the file filtering.
    - id: flake8
      name: flake8
      entry: flake8
      language: system
      types: [python]
