redis:
  image: redis:3.2.9-alpine
  command: redis-server --appendonly yes

postgres:
  image: postgres:9.6.3

web:
  build: .
  links:
    - redis:redis
    - postgres:postgres
  ports:
    # 5000 is occupied on recent versions of MacOS, lol
    - 12000:5000
  env_file:
    - .env

worker:
  build: .
  links:
    - redis:redis
    - postgres:postgres
  command: bin/worker --no-debug
  env_file:
    - .env
