#!/bin/bash
set -e
if [ ! -e venv/bin/activate ]; then
  virtualenv venv
fi
source venv/bin/activate
python setup.py develop
if [ "$1" == "bin/web" ]; then
  npm install
  npm run postinstall
fi
exec "$@"
