"""
add locked state to apps

Revision ID: cd83b3e2832e
Revises: 205fd513c96
Create Date: 2022-08-22 12:01:29.497845
"""

# revision identifiers, used by Alembic.
revision = "cd83b3e2832e"
down_revision = "205fd513c96"

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("app", sa.Column("locked_reason", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("app", "locked_reason")
    # ### end Alembic commands ###
